FROM node:20
WORKDIR /code

ARG NEXT_PUBLIC_API_USERNAME
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_PASSWORD

ENV NEXT_PUBLIC_API_USERNAME="$NEXT_PUBLIC_API_USERNAME"
ENV NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL"
ENV NEXT_PUBLIC_API_PASSWORD="$NEXT_PUBLIC_API_PASSWORD"

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD npm run start
